### ISSUE TITLE
ClosedChannelException when using the encryptingchannel with java.io streams

### ISSUE THREAD

**Issue by sixcorners** [exceptionfactory/jagged#3] opened 2024-03-12 10:52 UTC
Hello. I'm trying to use this with the old java.io streams and when I use Channels.newChannel/newOutputStream it causes issues when everything is to be closed. I made a unit test to reproduce what I am seeing. I'll send it as a PR.

**Comment by exceptionfactory** [comment] 2024-03-12 13:08
Thanks for providing the example in the linked pull request @sixcorners.

The problem is the result of `EncryptingChannel.close()` getting called multiple times, due to the declaration of the channel and the wrapping `OutputStream` in the initial try-with-resources block.

Declaring `OutputStream out4 = newOutputStream(out3)` creates a wrapping stream to be closed on completion of the block. As a result, the JVM calls both `out4.close()` and `out3.close()`, but `out4.close()` already calls `out3.close()` because it wraps the Channel.

For the purpose of this example, the `OutputStream` is not necessary, and the sample input could be written directly to the Channel using a `ByteBuffer` and calling `ByteBuffer.wrap()` around the content to be written. Removing that wrapping `OutputStream` avoids the repeated call to `EncryptingChannel.close()` and thus avoids the `ClosedChannelException`.

The `close()` method on the `EncryptingChannel` is important because it also sets a flag indicating that the last encrypted chunk has been written. In the `SimpleTest` example, `toByteArray()` is being called before `close()`, which means the encrypted payload is missing the final chunk information. Instead, the `ByteArrayOutputStream` should be declared outside of the try-with-resources block, and then `toByteArray()` should be called after the completion of the block. With that approach the final byte array will contain the formatted payload.

I will leave the pull request open for now for discussion of this example scenario.

**Comment by bendem** [comment] 2024-03-12 15:27
If I may, it might be a good idea to throw if calling `toByteArray()` before `close()` then. There is nothing worse than silent errors, especially in crypto code.

**Comment by exceptionfactory** [comment] 2024-03-12 16:24
> If I may, it might be a good idea to throw if calling `toByteArray()` before `close()` then. There is nothing worse than silent errors, especially in crypto code.

The `toByteArray()` method is specific to `ByteArrayOutputStream`, which is outside the control of the Jagged library, so in that particular case, the proper order of operations is the responsibility of the calling code.

**Comment by sixcorners** [comment] 2024-03-12 16:54
Ok. I changed it so that .close() is called before calling .toByteArray(). The use of ByteArrayOutputStream here is just to get the test working with information.

I don't know if there is a way to avoid calling close multiple times. If I'm sending data through a compression output stream then this channel then into a FileOutputStream I need to put all of these on their own line in a try with resources block if I want to make sure that all of them closed right? I could string them together on one line but then if any of the constructor calls fail then no close methods will get called.

**Comment by sixcorners** [comment] 2024-03-12 17:54
If I nest the construction of these things then if a constructor throws an exception then the try-with-resources block won't close any intermediate things that were constructed successfully.

I'm taking an inputstream from quarkus and passing that to a teeinputstream which is configured to copy the data to a zstdoutputstream which forwards to jagged which forwards to an s3outputstream written in kotlin then I'm parsing the info from the teeinputstream.

**Comment by sixcorners** [comment] 2024-03-12 18:38
Also I fixed the code in the PR. Thanks for the replies so far.

**Comment by sixcorners** [comment] 2024-03-12 18:44
Added a version that uses nested constructor calls that works. Should I be concerned about the constructors throwing exceptions?

**Comment by exceptionfactory** [comment] 2024-03-12 19:09
> Added a version that uses nested constructor calls that works. Should I be concerned about the constructors throwing exceptions?

Thanks for providing the additional example, the nested construction for the `OutputStream` wrapping the encrypting `Channel` provides a helpful comparison.

It sounds like a hybrid approach is the way to go. For example, declaring a `FileOutputStream` first makes sense, so it would be closed regardless of exceptions. For other wrapping streams and channels, separate declaration is not needed because there should be no need or ability to clean up from construction failures.

**Comment by exceptionfactory** [comment] 2024-03-12 20:37
That is a good point about the difference of behavior for `FileOutputStream.close()` versus `FileImageOutputStream.close()`. That highlights the importance of handling resource closure depending on the type of stream.

The `EncryptingChannel.close()` also closes the wrapped `WritableByteChannel` to prevent further writing after completion of encryption and buffer flush operations. `EncryptingChannel.close()` does not check status because calling `WritableByteChannel.close()` can throw the `ClosedChannelException` as observed.

For the use case in question, it might make sense close declare the `FileOutputStream` outside of the try block and close it in the finally block.

**Comment by sixcorners** [comment] 2024-03-13 06:20
The ImageOutputStreams are outliers. I think the pattern of putting each step into the try-with-resources block is a common practice so that nothing gets leaked and that it's fine to do so for things that don't really need to be closed like ByteArrayOutputStreams.

Also the contract of Closable.close() seems to say that it can be called multiple times.  
https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html#:~:text=If%20the%20stream%20is%20already%20closed%20then%20invoking%20this%20method%20has%20no%20effect

Do you think it would be possible or a good idea to change jagged to allow close() to be called multiple times?

**Comment by exceptionfactory** [comment] 2024-03-13 21:10
> Do you think it would be possible or a good idea to change jagged to allow close() to be called multiple times?

After reviewing the [Channel.close()](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/Channel.html#close--) documentation again and tracing the behavior of `EncryptingChannel.close()`, I realized that `EncryptingChannel.close()` is attempting to write another closing authentication tag to the end of the channel, resulting in the `ClosedChannelException`. From that angle, that should not be happening after the `close()` is already called.

All that to say, thanks for your patience in working through this issue. I will move forward with implementing a fix and publish a new version soon.

**Closed** 2024-03-14 16:51 UTC

**Comment by sixcorners** [comment] 2024-03-22 07:34
Sweet! Thanks!
